### ISSUE TITLE
Pictures missing

### ISSUE THREAD

**Issue by wilsonmar** [pcottle/PeterMCottle.com#1]
Peter,
Interesting navigation on the site.
Thought you'd like to know that there is a picture missing at
http://pcottle.github.io/PeterMCottle.com/?id=sd3&d=2

**Comment by pcottle** [comment]
Ah thanks Wilson! Yeah haha I was relying on a Facebook CDN permalink which
is very bad (since they expire and rotate). lemme go fix that real quick

On Sun, Aug 30, 2015 at 9:35 AM, Wilson Mar notifications@github.com
wrote:

> Peter,
> Thought you'd like to know that there is a picture missing at
> http://pcottle.github.io/PeterMCottle.com/?id=sd3&d=2
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pcottle/PeterMCottle.com/issues/1.

## 

Peter M Cottle
UC Berkeley Class of 2012
Master's of Science, Mechanical Engineering
UC San Diego Class of 2011
Bachelor's of Science, Mechanical Engineering
(408) 455 9405

"Equipped with his five senses, man explores the universe around him and
calls the adventure Science." - Edwin Hubble

**Comment by pcottle** [comment]
should be fixed! sorry my website is so out of date :P

On Sun, Aug 30, 2015 at 10:51 AM, Peter Cottle petermcottle@gmail.com
wrote:

> Ah thanks Wilson! Yeah haha I was relying on a Facebook CDN permalink
> which is very bad (since they expire and rotate). lemme go fix that real
> quick
> 
> On Sun, Aug 30, 2015 at 9:35 AM, Wilson Mar notifications@github.com
> wrote:
> 
> > Peter,
> > Thought you'd like to know that there is a picture missing at
> > http://pcottle.github.io/PeterMCottle.com/?id=sd3&d=2
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/pcottle/PeterMCottle.com/issues/1.
> 
> ## 
> 
> Peter M Cottle
> UC Berkeley Class of 2012
> Master's of Science, Mechanical Engineering
> UC San Diego Class of 2011
> Bachelor's of Science, Mechanical Engineering
> (408) 455 9405
> 
> "Equipped with his five senses, man explores the universe around him and
> calls the adventure Science." - Edwin Hubble

## 

Peter M Cottle
UC Berkeley Class of 2012
Master's of Science, Mechanical Engineering
UC San Diego Class of 2011
Bachelor's of Science, Mechanical Engineering
(408) 455 9405

"Equipped with his five senses, man explores the universe around him and
calls the adventure Science." - Edwin Hubble
